// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yekchkfacataeesevada.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inlla2Noa2ZhY2F0YWVlc2V2YWRhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI1MzQ4NDMsImV4cCI6MjA2ODExMDg0M30.4bVXl8kstAeMAYTGMGKbDmMW6LdBSr4tgb2pl9JvoG4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});